apiVersion: v1 #Version of the kubernetes Api Version / v1, apps/v1
kind: Pod # Object type / Pod (v1), Service (v1), ReplicaSet (apps/v1), Deployment (apps/v1)
metadata: # Metadata about the object / Only allows name and labels as children
  name: myapp-pod
  labels: # Any keyValue we want to identify the pod
    app: myapp
    type: front-end
spec: # Object Specification / This will be different for each object type
  #   tolerations:
  #   - key: "app"
  #     operator: "equal"
  #     value: "blue"
  #     effect: "NoSchedule"
  # nodeSelector:
  #   nodeLabelKey: nodeLabelValue # kubectl label nodes <node-name> <label-key>=<label-value>
  # affinity:
  #   nodeAffinity:
  #     raquiredDuringSchedulingIngnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: size #Nodetag key
  #           operator: In # In, NotIn, Exists, ...
  #           values:
  #           - Large
  #           - Medium
  containers: # Array / Allows multiple containers
    - name: nginx-container # - refers to the item in list
      image: nginx
      ports:
        - containerPod: 8080
      env:
        - name: ENV_VARIABLE_NAME
          value: "envVariableValue"
        - name: ENV_VARIABLE_NAME_CONFIGMAP
          valueFrom:
            configMapKeyRef:
        - name: ENV_VARIABLE_NAME_SECRET
          valueFrom:
            secretKeyRef: 
      envFrom:
      - configMapRef:
          name: configMap-name
      - secretRef:
          name: secret-name
      - secretRef:
          name: secret-name2
          key: specific-secret
      resources:
        limits:
          memory: 20Mi
        requests:
          memory: 5Mi