apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: bXlzcWw=         #echo -n "mysql"| base64
  DB_USER: dXNlcg==         #echo -n "user"| base64
  DB_PASSWORD: cGFzc3dvcmQ= #echo -n "password"| base64